language: ruby
before_install:
  - gem install ffi rubygems-tasks rspec yard kramdown
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
script: rake spec
